### PR TITLE
adding readme file

### PR DESCRIPTION
**Pull request by Ramsha196**

### CODE REVIEW

**Review by MrSlimCoder — APPROVED** [review]

**Comment by MrSlimCoder** [comment]
Thank you so much @Ramsha196  for your contribution .

**Comment by viveksharmaui** [comment]
@all-contributors please add @Ramsha196 for code

**Comment by MrSlimCoder** [comment]
@all-contributors please add @Ramsha196 for code

**Comment by viveksharmaui** [comment]
@allcontribitors please add @viveksharmaui for infrastructure test code

**Comment by MrSlimCoder** [comment]
@allcontributors please add @viveksharmaui for infrastructure test and code

**Comment by MrSlimCoder** [comment]
@allcontributors add @Ramsha196 for doc

**Pull request merged**
